FROM python:3.12.6-slim
RUN mkdir workspace
WORKDIR /workspace
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean
RUN pip install "poetry"
RUN poetry config virtualenvs.create false
ENV PYTHONPATH=/workspace/src:${PYTHONPATH}
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root
COPY . .