services:
  diplomado-ciencia-datos:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/bash"
    stdin_open: true
    tty: true
    container_name: diplomado-ciencia-datos
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    env_file:
      - .env