services:
  api-clustering:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-clustering:latest
    container_name: api-clustering
    command: "gunicorn -b 0.0.0.0:5000 app:app"
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
